### ISSUE TITLE
cant build app with --prod flag.

### ISSUE THREAD

**Issue by Ramachandrajoshi** [leonardosalles/ionic2-zoom-area#17]
![screen shot 2018-07-14 at 5 43 22 pm](https://user-images.githubusercontent.com/14068607/42724313-7f1f72f4-878d-11e8-8aa3-214e4cb196dc.png)
getting this error while building the app with --prod flag.
Please solve this error.
pinch zoom is not stable.
initially half image will show at the bottom of that page.

**Comment by phikani** [comment]
Hi,

I'm having the same problem. 
In the GIT repo it is said to be fixed, nevertheless I am not able to build my Ionic app for production.
Tried different things but could not find a solution. 

@leonardosalles Do you have an idea how to solve this? Your help would really be appreciated. I really like the plugin and it is very important for my application.

Thanks a lot in advance!

**Comment by Ramachandrajoshi** [comment]
No. Still facing same issue.

**Comment by leonardosalles** [comment]
You guys are facing the same issue in Example app? if yes, need to check angular-cli version and ionic-app-scripts version, my suggestion is to update all these dependencies to the latest version.

**Comment by Ivan-Perez** [comment]
I also have this issue. I have updated both angular-cli and ionic-app-scripts to their latest versions and compilation fails:

```
$ ionic cordova build android --prod --release
Running app-scripts build: --prod --platform android --target cordova
[15:10:29]  build prod started ...
[15:10:29]  clean started ...
[15:10:29]  clean finished in 10 ms
[15:10:29]  copy started ...
[15:10:29]  deeplinks started ...
[15:10:29]  deeplinks finished in 46 ms
[15:10:29]  ngc started ...
[15:10:35]  typescript error
            ionic2-zoom-area\dist\zoom-area.module.ts(6,2): Error during template compile of 'ZoomAreaModule' Function
            expressions are not supported in decorators in 'NgModule' 'NgModule' contains the error at
            @angular\core\core.ts(194,31) Consider changing the function expression into an exported function.

Error: The Angular AoT build failed. See the issues above
    at ...\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (...\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (...\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (...\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>
[15:10:36]  copy finished in 6.51 s
```

**Comment by phikani** [comment]
I also tried with updating the cli and ionic-app-scripts, but I am still facing the same issue. I receive exactly the same message as you do, @Ivan-Perez . This is really problematic as the loading time for compiling the app without --prod flag is much higher...

@Ivan-Perez , I opened another [issue ](https://github.com/leonardosalles/ionic2-zoom-area/issues/18) a few days ago because the control buttons change their state of being visible or invisible whenever I somehow interact with the image (SVG) in my page... I use the zoom area in combination with a SVG image on which I add markers... Whenever I add a marker to the image, the controls disappear if they were shown and the other way round... Any suggestions for this maybe? Do you experience the same? 

Thanks a lot and kind regards

Philipp
