### ISSUE TITLE
library requires angular animations, docs should mention it

### ISSUE THREAD

**Issue by jimmy-tfp** [leonardosalles/ionic2-zoom-area#4]
you need to run 
```npm install @angular/animations --save```
or this directive will not compile

**Comment by christianwico** [comment]
I have this issue as well. I installed @angular/animations (v4.4.4). What do I need to import?

**Comment by leonardosalles** [comment]
It just depends on angular animations 4.4.4. What is the exactly error that you guys have? Can someone please add your console output

**Comment by jimmy-tfp** [comment]
the error is:
```
Runtime Error
Cannot find module "@angular/animations"
Stack
Error: Cannot find module "@angular/animations"
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:78901:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:119250:79)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.257 (http://localhost:8100/build/main.js:96:75)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.252 (http://localhost:8100/build/main.js:78:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1
```

**Comment by leonardosalles** [comment]
Info was added to README file, closing the issue. [commit 9d21fbc](https://github.com/leonardosalles/ionic2-zoom-area/commit/5c8f813f42f8113269a64128e83c24533029aa90)
